### PR TITLE
Add moodle unicode unspoof

### PR DESCRIPTION
**Pull request by uvoglu**
- Adds a simple page to replace spoofed unicode characters back to their normal character.
- Useful if Lehrers try to make your life hard on Moodle tests by preventing easy copy pasting.

### Example
`prеfix("id")(2) == "id2"` is being replaced to `prefix("id")(2) == "id2"`

(Note that VS Code displays a warning for the `e` in the first string, because it's not a usual e (Unicode `U+0065`) but a Cyrillic letter instead (Unicode `U+0435`), which looks really similar.

### CODE REVIEW

**Review by riesentoaster — APPROVED** [review]

**Comment by uvoglu** [comment]
pls merge, I think I don't have the permission to do so.

**Comment by uvoglu** [comment]
I moved it to a dedicated domain, so the link in the readme now just points to this link.

**Comment by riesentoaster** [comment]
That's fine too.

One more thing: Add yourself to the contributors list at the bottom of `README.md`.

**Comment by uvoglu** [comment]
Oh of course, I have done so now 😁

**Pull request merged**
