### PR TITLE
Adding a famous quote by bohe

### PR DESCRIPTION
**Pull request by Geissemanu**

### CODE REVIEW

**Review by riesentoaster — CHANGES_REQUESTED** [review]
Change pr title

**Review by riesentoaster — CHANGES_REQUESTED** [review]
Now do it again.

**Review by riesentoaster — CHANGES_REQUESTED** [review]
GOTO 0

**Review by riesentoaster — CHANGES_REQUESTED** [review]
That is rude and against community guidelines.

**Review by Geissemanu — COMMENTED** [review]
change it i hate it.

**Review by riesentoaster — COMMENTED** [review]
Can I get a list of proposals?

**Comment by Geissemanu** [comment]
update/quotes
feature/quote-update
quotes/additional-quotes
quotes/fix-typos
quotes/remove-duplicates
markdown/quote-updates
quotes/new-arrivals
quotes/delete-obsolete-quotes
quotes/formatting-updates
quotes/translation-updates

**Comment by riesentoaster** [comment]
1. "Apple Caught Red-Handed: Professor Bohnert Says They Stole from Open Source Community"
1. "Bohnert's Burn: Apple Gets Called Out for Taking from Open Source"
1. "The Great Open Source Heist: Professor Bohnert Puts Apple on Blast"
1. "Open Source Community to Apple: Stop Taking Our Stuff! Professor Bohnert Agrees"
1. "Who Stole the Cookie from the Open Source Jar? Professor Bohnert Says It's Apple!"

Opinions?

**Comment by Geissemanu** [comment]
Apple Takes a Byte Out of Open Source: Professor Bohnert Exposes the Theft
Bohnert vs. The Big Apple: A Tale of Open Source Betrayal
Apple Picking from the Open Source Orchard: Professor Bohnert Sounds the Alarm
The Apple Doesn't Fall Far from the Open Source Tree: Professor Bohnert Speaks Out
The Open Source Avengers Assemble Against Apple: Professor Bohnert Leads the Charge
The Great Open Source Caper: Professor Bohnert Busts Apple in the Act
Apple's Sticky Fingers: Professor Bohnert Calls Out the Open Source Plagiarism
The Open Source Code War: Apple vs. Professor Bohnert and the Community
An Apple a Day Keeps the Open Source Community in Disarray: Professor Bohnert Fights Back
The Empire Strikes Back: Professor Bohnert and the Rebels Take on Apple's Open Source Theft

**Comment by riesentoaster** [comment]
1. "Apple's Generosity Knows No Bounds: Bohnert Reveals Their 'Donations' from Open Source"
1. "Who Needs Ethics When You Have Apple? Bohnert Calls Out Open Source Theft"
1. "Apple's Little Secret: Bohnert Exposes Their Not-So-Open Source Practices"
1. "Bohnert Drops the Truth Bomb on Apple's Open Source Theft"
1. "Apple's Open Source 'Contribution': Bohnert Says It's Time to Give Credit Where It's Due"

**Review by riesentoaster — APPROVED** [review]
Let's merge this and focus our energy on working with advanced technology™️

**Pull request merged**
