### PR TITLE
Nothing/squaring the circle

### PR DESCRIPTION
**Pull request by Geissemanu**

### CODE REVIEW

**Comment by riesentoaster** [comment]
Is that a `nothing`?

**Comment by Geissemanu** [comment]
Definition of nothing 
1: not any thing : no thing

**Comment by riesentoaster** [comment]
Also: Can I point you to https://github.com/riesentoaster/geiman01/discussions/categories/thingification

**Review by riesentoaster — APPROVED** [review]

**Comment by MrF3lix** [comment]
@Geissemanu pls merge

**Pull request merged**
